## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - PROVIDER-INFRA-SETUP
  - STATEFUL-APP-DEPLOY
  - APP-FUNC-TEST
  - APP-CHAOS-TEST
  - APP-DEPROVISION
  - CLUSTER-CLEANUP

variables: 
  utils_path: "/openebs/e2e-aws/script/utils"

## Setup the kubernetes cluster

aws-cluster:
  image: atulabhi/kops:v8
  stage: CLUSTER-SETUP 
  script: 
    - ./script/aws
  artifacts:
    paths:
      - aws/

## Setup OpenEBS control plane

openebs-aws-deploy:
  image: atulabhi/kops:v8
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - aws-cluster
  script: 
   - ./script/provider/infra-setup
  artifacts:
    paths:
      - aws-openebs/

openebs-sc-deploy:
  image: atulabhi/kops:v8
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - aws-cluster
  script: 
   - ./script/provider/setup-sc
  artifacts:
    paths:
      - aws-openebs/

## Define a job template for app deployers

.app_deploy_template:
  image: atulabhi/kops:v8
  stage: STATEFUL-APP-DEPLOY 
  dependencies:
    - openebs-aws-deploy
  artifacts:
    paths: 
      - aws-openebs/

## Define the app deployer jobs

## PERCONA-JIVA

# PERCONA-CSTOR
percona-cstor-run/load/check 0:2:
  extends: .app_deploy_template
  script: 
   - ./script/apps/percona/deployer/percona-app-deploy-cstor

percona-cstor-run/load/check 1:2:
  extends: .app_deploy_template
  before_script: 
   - sleep 180
  script: 
   - ./script/apps/percona/workload/cstor/percona-app-workload-cstor


## Define job template for func test jobs  

.func_test_template:
  image: atulabhi/kops:v8
  stage: APP-FUNC-TEST
  when: always 
  artifacts:
    paths: 
      - aws-openebs/

cstor-k8s-snapshot-clone-creation-{snapshot-clone-cStor}:
  extends: .func_test_template
  script:
   - ./script/apps/percona/functional/cstor/k8s-snapshot-clone-cstor


cleanup-aws:
  when: always
  image: atulabhi/kops:v8
  dependencies:
    - aws-cluster
  stage: CLUSTER-CLEANUP
  script: 
    - chmod 755 ./script/aws-cleanup
    - ./script/aws-cleanup
